spring:
  application:
    name: loyalty-service
  datasource:
    url: jdbc:postgresql://localhost:5432/autocare_loyalty
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html