# ConfiguraciÃ³n del servidor y puerto donde correrÃ¡ la aplicaciÃ³n
# PORT: variable de entorno opcional, por defecto 8081
server:
  port: ${PORT:8081}

# ConfiguraciÃ³n de Spring Boot
spring:
  cloud:
    compatibility-verifier:
      enabled: false
  # Nombre de la aplicaciÃ³n en el contexto de Spring/Eureka
  application:
    name: garage-service
  # ConfiguraciÃ³n de la fuente de datos (base de datos)
  datasource:
    # DB_URL: url de conexiÃ³n JDBC, por defecto apunta a Postgres local
    url: ${DB_URL:jdbc:postgresql://localhost:5432/autocare_garage}
    # DB_USER: usuario de la BD
    username: ${DB_USER:postgres}
    # DB_PASSWORD: contraseÃ±a de la BD
    password: ${DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: 3
  # ConfiguraciÃ³n de JPA/Hibernate
  jpa:
    hibernate:
      # ddl-auto controla creaciÃ³n/actualizaciÃ³n de esquema: 'update' por defecto
      ddl-auto: update
    # Mostrar consultas SQL en consola
    show-sql: true
    properties:
      hibernate:
        # Formatear SQL al mostrarlo
        format_sql: true
        # Dialecto de Hibernate para PostgreSQL
        dialect: org.hibernate.dialect.PostgreSQLDialect

# ConfiguraciÃ³n de Eureka (servicio de descubrimiento)
eureka:
  client:
    serviceUrl:
      # EUREKA_URI: URL del servidor Eureka, por defecto localhost:8761/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    # Preferir la direcciÃ³n IP en la instancia registrada en Eureka
    prefer-ip-address: true

# ConfiguraciÃ³n de SpringDoc / Swagger para documentaciÃ³n de la API
springdoc:
  api-docs:
    # Habilitar generaciÃ³n de OpenAPI/Swagger JSON
    enabled: true
  swagger-ui:
    # Habilitar interfaz Swagger UI
    enabled: true
    # Ruta donde estarÃ¡ disponible la UI de Swagger
    path: /doc/swagger-ui.html

