server:
  port: ${PORT:8090}

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: analytics-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/autocare_analytics}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
